
module "aws_rds" {
  source                                  = "../modules/rds/"
  rds_instance_volume_size                = "${var.rds_instance_volume_size}"
  rds_instance_engine_version             = "${var.rds_instance_engine_version}"
  rds_instance_storage_type               = "${var.rds_instance_storage_type}"
  rds_instance_engine                     = "${var.rds_instance_engine}"
  rds_instance_class                      = "${var.rds_instance_class}"
  rds_instance_name                       = "${var.rds_instance_name}"
  rds_instance_username                   = "${var.rds_instance_username}"
  rds_instance_password                   = "${var.rds_instance_password}"
  rds_instance_parameter_group_name       = "${var.rds_instance_parameter_group_name}"
  rds_instance_allow_major_version_update = "${var.rds_instance_allow_major_version_update}"
  rds_instance_apply_immediately          = "${var.rds_instance_apply_immediately}"
  rds_instance_auto_minor_version_upgrade = "${var.rds_instance_auto_minor_version_upgrade}"
  rds_instance_az                         = "${var.rds_instance_az}"
  rds_instance_backup_retention_period    = "${var.rds_instance_backup_retention_period}"
  rds_instance_backup_window              = "${var.rds_instance_backup_window}"
  rds_instance_db_subnet_group_name       = "${var.rds_instance_db_subnet_group_name}"
  rds_instance_maintenance_window         = "${var.rds_instance_maintenance_window}"
  rds_instance_multi_az                   = "${var.rds_instance_multi_az}"
  rds_instance_option_group_name          = "${var.rds_instance_option_group_name}"
  rds_instance_publicly_accessible        = "${var.rds_instance_publicly_accessible}"
  rds_instance_skip_final_snapshot        = "${var.rds_instance_skip_final_snapshot}"
  rds_instance_storage_encrypted          = "${var.rds_instance_storage_encrypted}"
  rds_instance_vpc_security_group_ids     = "${var.rds_instance_vpc_security_group_ids}"
  rds_instance_tags                       = "${var.rds_instance_tags}"
}
