terraform {
  backend "s3" {}
}

locals {
  fips_endpoints =  {
    acm = "${var.fips ? "https://acm-fips.us-east-1.amazonaws.com" : ""}"
    acmpca = "${var.fips ? "https://acm-pca-fips.us-east-1.amazonaws.com" : ""}"
    apigateway = "${var.fips ? "https://apigateway-fips.us-east-1.amazonaws.com" : ""}"
    appstream = "${var.fips ? "https://appstream2-fips.us-east-1.amazonaws.com" : ""}"
    cloudformation = "${var.fips ? "https://cloudformation-fips.us-east-1.amazonaws.com" : ""}"
    cloudfront = "${var.fips ? "https://cloudfront-fips.amazonaws.com" : ""}"
    cloudtrail = "${var.fips ? "https://cloudtrail-fips.us-east-1.amazonaws.com" : ""}"
    codebuild = "${var.fips ? "https://codebuild-fips.us-east-1.amazonaws.com" : ""}"
    codecommit = "${var.fips ? "https://codecommit-fips.us-east-1.amazonaws.com" : ""}"
    codedeploy = "${var.fips ? "https://codedeploy-fips.us-east-1.amazonaws.com" : ""}"
    cognitoidentity = "${var.fips ? "https://cognito-identity-fips.us-east-1.amazonaws.com" : ""}"
    cognitoidp = "${var.fips ? "https://cognito-idp-fips.us-east-1.amazonaws.com" : ""}"
    configservice = "${var.fips ? "https://config-fips.us-east-1.amazonaws.com" : ""}"
    datasync = "${var.fips ? "https://datasync-fips.us-east-1.amazonaws.com" : ""}"
    directconnect = "${var.fips ? "https://directconnect-fips.us-east-1.amazonaws.com" : ""}"
    dms = "${var.fips ? "https://dms-fips.us-east-1.amazonaws.com" : ""}"
    ds = "${var.fips ? "https://ds-fips.us-east-1.amazonaws.com" : ""}"
    dynamodb = "${var.fips ? "https://dynamodb-fips.us-east-1.amazonaws.com" : ""}"
    ec2 = "${var.fips ? "https://ec2-fips.us-east-1.amazonaws.com" : ""}"
    ecr = "${var.fips ? "https://ecr-fips.us-east-1.amazonaws.com" : ""}"
    elasticache = "${var.fips ? "https://elasticache-fips.us-east-1.amazonaws.com" : ""}"
    elasticbeanstalk = "${var.fips ? "https://elasticbeanstalk-fips.us-east-1.amazonaws.com" : ""}"
    elb = "${var.fips ? "https://elasticloadbalancing-fips.us-east-1.amazonaws.com" : ""}"
    emr = "${var.fips ? "https://elasticmapreduce-fips.us-east-1.amazonaws.com" : ""}"
    es = "${var.fips ? "https://es-fips.us-east-1.amazonaws.com" : ""}"
    fms = "${var.fips ? "https://fms-fips.us-east-1.amazonaws.com" : ""}"
    glacier = "${var.fips ? "https://glacier-fips.us-east-1.amazonaws.com" : ""}"
    guardduty = "${var.fips ? "https://guardduty-fips.us-east-1.amazonaws.com" : ""}"
    inspector = "${var.fips ? "https://inspector-fips.us-east-1.amazonaws.com" : ""}"
    kinesis = "${var.fips ? "https://kinesis-fips.us-east-1.amazonaws.com" : ""}"
    kms = "${var.fips ? "https://kms-fips.us-east-1.amazonaws.com" : ""}"
    lambda = "${var.fips ? "https://lambda-fips.us-east-1.amazonaws.com" : ""}"
    mq = "${var.fips ? "https://mq-fips.us-east-1.amazonaws.com" : ""}"
    pinpoint = "${var.fips ? "https://pinpoint-fips.us-east-1.amazonaws.com" : ""}"
    quicksight = "${var.fips ? "https://fips-us-east-1.quicksight.aws.amazon.com" : ""}"
    rds = "${var.fips ? "https://rds-fips.us-east-1.amazonaws.com" : ""}"
    redshift = "${var.fips ? "https://redshift-fips.us-east-1.amazonaws.com" : ""}"
    resourcegroups = "${var.fips ? "https://resource-groups-fips.us-east-1.amazonaws.com" : ""}"
    route53 = "${var.fips ? "https://route53-fips.amazonaws.com" : ""}"
    s3 = "${var.fips ? "https://s3-fips.us-east-1.amazonaws.com" : ""}"
    sagemaker = "${var.fips ? "https://api-fips.sagemaker.us-east-1.amazonaws.com" : ""}"
    secretsmanager = "${var.fips ? "https://secretsmanager-fips.us-east-1.amazonaws.com" : ""}"
    servicecatalog = "${var.fips ? "https://servicecatalog-fips.us-east-1.amazonaws.com" : ""}"
    ses = "${var.fips ? "https://email-fips.us-east-1.amazonaws.com" : ""}"
    shield = "${var.fips ? "https://shield-fips.us-east-1.amazonaws.com" : ""}"
    sns = "${var.fips ? "https://sns-fips.us-east-1.amazonaws.com" : ""}"
    sqs = "${var.fips ? "https://sqs-fips.us-east-1.amazonaws.com" : ""}"
    ssm = "${var.fips ? "https://ssm-fips.us-east-1.amazonaws.com" : ""}"
    sts = "${var.fips ? "https://sts-fips.us-east-1.amazonaws.com" : ""}"
    swf = "${var.fips ? "https://swf-fips.us-east-1.amazonaws.com" : ""}"
    waf = "${var.fips ? "https://waf-fips.amazonaws.com" : ""}"
    wafregional = "${var.fips ? "https://waf-regional-fips.us-east-1.amazonaws.com" : ""}"
    wafv2 = "${var.fips ? "https://wafv2-fips.us-east-1.amazonaws.com" : ""}"
  }
}

provider "aws" {
  version = "= 3.28.0"
  endpoints  {
    acm = "${local.fips_endpoints["acm"]}"
    acmpca = "${local.fips_endpoints["acmpca"]}"
    apigateway = "${local.fips_endpoints["apigateway"]}"
    appstream = "${local.fips_endpoints["appstream"]}"
    cloudformation = "${local.fips_endpoints["cloudformation"]}"
    cloudfront = "${local.fips_endpoints["cloudfront"]}"
    cloudtrail = "${local.fips_endpoints["cloudtrail"]}"
    codebuild = "${local.fips_endpoints["codebuild"]}"
    codecommit = "${local.fips_endpoints["codecommit"]}"
    codedeploy = "${local.fips_endpoints["codedeploy"]}"
    cognitoidentity = "${local.fips_endpoints["cognitoidentity"]}"
    cognitoidp = "${local.fips_endpoints["cognitoidp"]}"
    configservice = "${local.fips_endpoints["configservice"]}"
    datasync = "${local.fips_endpoints["datasync"]}"
    directconnect = "${local.fips_endpoints["directconnect"]}"
    dms = "${local.fips_endpoints["dms"]}"
    ds = "${local.fips_endpoints["ds"]}"
    dynamodb = "${local.fips_endpoints["dynamodb"]}"
    ec2 = "${local.fips_endpoints["ec2"]}"
    ecr = "${local.fips_endpoints["ecr"]}"
    elasticache = "${local.fips_endpoints["elasticache"]}"
    elasticbeanstalk = "${local.fips_endpoints["elasticbeanstalk"]}"
    elb = "${local.fips_endpoints["elb"]}"
    emr = "${local.fips_endpoints["emr"]}"
    es = "${local.fips_endpoints["es"]}"
    fms = "${local.fips_endpoints["fms"]}"
    glacier = "${local.fips_endpoints["glacier"]}"
    guardduty = "${local.fips_endpoints["guardduty"]}"
    inspector = "${local.fips_endpoints["inspector"]}"
    kinesis = "${local.fips_endpoints["kinesis"]}"
    kms = "${local.fips_endpoints["kms"]}"
    lambda = "${local.fips_endpoints["lambda"]}"
    mq = "${local.fips_endpoints["mq"]}"
    pinpoint = "${local.fips_endpoints["pinpoint"]}"
    quicksight = "${local.fips_endpoints["quicksight"]}"
    rds = "${local.fips_endpoints["rds"]}"
    redshift = "${local.fips_endpoints["redshift"]}"
    resourcegroups = "${local.fips_endpoints["resourcegroups"]}"
    route53 = "${local.fips_endpoints["route53"]}"
    s3 = "${local.fips_endpoints["s3"]}"
    sagemaker = "${local.fips_endpoints["sagemaker"]}"
    secretsmanager = "${local.fips_endpoints["secretsmanager"]}"
    servicecatalog = "${local.fips_endpoints["servicecatalog"]}"
    ses = "${local.fips_endpoints["ses"]}"
    shield = "${local.fips_endpoints["shield"]}"
    sns = "${local.fips_endpoints["sns"]}"
    sqs = "${local.fips_endpoints["sqs"]}"
    ssm = "${local.fips_endpoints["ssm"]}"
    sts = "${local.fips_endpoints["sts"]}"
    swf = "${local.fips_endpoints["swf"]}"
    waf = "${local.fips_endpoints["waf"]}"
    wafregional = "${local.fips_endpoints["wafregional"]}"
    wafv2 = "${local.fips_endpoints["wafv2"]}"
  }
}

module "aws_rds" {
  source                                             = "../modules/rds/"
  rds_instance_allocated_storage                     = "${var.rds_instance_allocated_storage}"
  rds_instance_allow_major_version_upgrade           = "${var.rds_instance_allow_major_version_upgrade}"
  rds_instance_apply_immediately                     = "${var.rds_instance_apply_immediately}"
  rds_instance_auto_minor_version_upgrade            = "${var.rds_instance_auto_minor_version_upgrade}"
  rds_instance_availability_zone                     = "${var.rds_instance_availability_zone}"
  rds_instance_backup_retention_period               = "${var.rds_instance_backup_retention_period}"
  rds_instance_backup_window                         = "${var.rds_instance_backup_window}"
  rds_instance_character_set_name                    = "${var.rds_instance_character_set_name}"
  rds_instance_copy_tags_to_snapshot                 = "${var.rds_instance_copy_tags_to_snapshot}"
  rds_instance_create_monitoring_role                = "${var.rds_instance_create_monitoring_role}"
  rds_instance_create                                = "${var.rds_instance_create}"
  rds_instance_db_subnet_group_name                  = "${var.rds_instance_db_subnet_group_name}"
  rds_instance_deletion_protection                   = "${var.rds_instance_deletion_protection}"
  rds_instance_enabled_cloudwatch_logs_exports       = "${var.rds_instance_enabled_cloudwatch_logs_exports}"
  rds_instance_engine                                = "${var.rds_instance_engine}"
  rds_instance_engine_version                        = "${var.rds_instance_engine_version}"
  rds_instance_final_snapshot_identifier             = "${var.rds_instance_final_snapshot_identifier}"
  rds_instance_iam_database_authentication_enabled   = "${var.rds_instance_iam_database_authentication_enabled}"
  rds_instance_identifier                            = "${var.rds_instance_identifier}"
  rds_instance_instance_class                        = "${var.rds_instance_instance_class}"
  rds_instance_iops                                  = "${var.rds_instance_iops}"
  rds_instance_kms_key_id                            = "${var.rds_instance_kms_key_id}"
  rds_instance_license_model                         = "${var.rds_instance_license_model}"
  rds_instance_maintenance_window                    = "${var.rds_instance_maintenance_window}"
  rds_instance_max_allocated_storage                 = "${var.rds_instance_max_allocated_storage}"
  rds_instance_monitoring_interval                   = "${var.rds_instance_monitoring_interval}"
  rds_instance_monitoring_role_arn                   = "${var.rds_instance_monitoring_role_arn}"
  rds_instance_monitoring_role_name                  = "${var.rds_instance_monitoring_role_name}"
  rds_instance_multi_az                              = "${var.rds_instance_multi_az}"
  rds_instance_name                                  = "${var.rds_instance_name}"
  rds_instance_option_group_name                     = "${var.rds_instance_option_group_name}"
  rds_instance_parameter_group_name                  = "${var.rds_instance_parameter_group_name}"
  rds_instance_password                              = "${var.rds_instance_password}"
  rds_instance_performance_insights_enabled          = "${var.rds_instance_performance_insights_enabled}"
  rds_instance_performance_insights_retention_period = "${var.rds_instance_performance_insights_retention_period}"
  rds_instance_port                                  = "${var.rds_instance_port}"
  rds_instance_publicly_accessible                   = "${var.rds_instance_publicly_accessible}"
  rds_instance_replicate_source_db                   = "${var.rds_instance_replicate_source_db}"
  rds_instance_skip_final_snapshot                   = "${var.rds_instance_skip_final_snapshot}"
  rds_instance_snapshot_identifier                   = "${var.rds_instance_snapshot_identifier}"
  rds_instance_storage_encrypted                     = "${var.rds_instance_storage_encrypted}"
  rds_instance_storage_type                          = "${var.rds_instance_storage_type}"
  rds_instance_tags                                  = "${var.rds_instance_tags}"
  rds_instance_timezone                              = "${var.rds_instance_timezone}"
  rds_instance_username                              = "${var.rds_instance_username}"
  rds_instance_vpc_security_group_ids                = "${var.rds_instance_vpc_security_group_ids}"

  rds_instance_backup_enabled                        = "${var.rds_instance_backup_enabled}"
  rds_instance_backup_kms_key                        = "${var.rds_instance_backup_kms_key}"
  rds_instance_backup_bucket_name                    = "${var.rds_instance_backup_bucket_name}"
}
