{
 "title": "CI Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ci_metrics" }
  ]
 },
 "panels": [
  {
   "title": "Failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "pr_num" ], "type": "tag" },
      { "params": [ "repo_name" ], "type": "tag" },
      { "params": [ "suite_name" ], "type": "tag" }
     ],
     "measurement": "fail_count",
     "select": [
      [
       { "params": [ "fail_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Successes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "pr_num" ], "type": "tag" },
      { "params": [ "repo_name" ], "type": "tag" },
      { "params": [ "suite_name" ], "type": "tag" }
     ],
     "measurement": "pass_count",
     "select": [
      [
       { "params": [ "pass_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FAILING SUITES",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "suite_name" ], "type": "tag" }
     ],
     "measurement": "fail_count",
     "select": [
      [
       { "params": [ "fail_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Successes Per PR",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "repo_name" ], "type": "tag" },
      { "params": [ "pr_num" ], "type": "tag" }
     ],
     "measurement": "pass_count",
     "select": [
      [
       { "params": [ "pass_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Successes" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failures Per PR",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "repo_name" ], "type": "tag" },
      { "params": [ "pr_num" ], "type": "tag" }
     ],
     "measurement": "fail_count",
     "select": [
      [
       { "params": [ "fail_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Failures" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Retries Per PR",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "repo_name" ], "type": "tag" },
      { "params": [ "pr_num" ], "type": "tag" }
     ],
     "measurement": "retry_count",
     "select": [
      [
       { "params": [ "retry_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Retries" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "SELENIUM GRID SESSIONS",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "pr_num" ], "type": "tag" },
      { "params": [ "test_name" ], "type": "tag" },
      { "params": [ "selenium_grid_sessions" ], "type": "tag" }
     ],
     "measurement": "fail_count",
     "query": "SELECT sum(\"fail_count\") FROM \"fail_count\" WHERE $timeFilter GROUP BY \"selenium_grid_sessions\"",
     "select": [
      [
       { "params": [ "fail_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Duration of tests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "suite_name" ], "type": "tag" },
      { "params": [ "test_name" ], "type": "tag" }
     ],
     "measurement": "run_time",
     "select": [
      [
       { "params": [ "run_time" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "FAILING TESTS",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "suite_name" ], "type": "tag" },
      { "params": [ "test_name" ], "type": "tag" }
     ],
     "measurement": "fail_count",
     "select": [
      [
       { "params": [ "fail_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TEST RETRIES",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "suite_name" ], "type": "tag" },
      { "params": [ "test_name" ], "type": "tag" }
     ],
     "measurement": "retry_count",
     "select": [
      [
       { "params": [ "retry_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}