{
 "title": "Jenkins monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "CPU usage by Pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n    rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container_name=\"jenkins\"}[5m])\n) by (container_name)",
     "legendFormat": "{{container_name}}"
    },
    {
     "expr": "sum(    rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container_name=\"selenium\"}[5m])) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Memory usage by Pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"$namespace\", container_name=\"jenkins\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"$namespace\", container_name=~\"selenium\"}) by (container_name)",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Containers Restarts (Last 30 Minutes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total{namespace=~\"$namespace\", pod=~\"jenkins-.*\"}[30m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{persistentvolumeclaim=\"datadir-jenkins\"} / kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=\"datadir-jenkins\"} * 100",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}