{
 "title": "Selenium Observability",
 "description": "Selenium Observability",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "Grid UP",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 2, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(selenium_grid_up{kubernetes_namespace=\"default\"})"
    }
   ]
  },
  {
   "title": "Selenium Hub uptime",
   "type": "graph",
   "gridPos": { "h": 9, "w": 3, "x": 2, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(selenium_grid_up{kubernetes_namespace=\"default\"})"
    }
   ]
  },
  {
   "title": "Hub Sessions Backlog",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(selenium_grid_hub_sessions_backlog{kubernetes_namespace=\"default\"}[5m])) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Hub Slots Free",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(selenium_grid_hub_slotsFree{kubernetes_namespace=\"default\"}[5m])) by (kubernetes_pod_name)"
    }
   ]
  },
  {
   "title": "Hub Slots Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 5, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(selenium_grid_hub_slotsTotal{kubernetes_namespace=\"default\"}[5m])) by (kubernetes_pod_name)"
    }
   ]
  },
  {
   "title": "Hub CPU activity",
   "type": "graph",
   "gridPos": { "h": 13, "w": 5, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(    rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container_name=\"hub\"}[5m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Hub Memory Usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 5, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(    rate(container_memory_usage_bytes{namespace=~\"$namespace\", container_name=\"hub\"}[5m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Nodes CPU activity",
   "type": "graph",
   "gridPos": { "h": 13, "w": 5, "x": 11, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(    rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container_name=\"node-chrome\"}[5m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Nodes Memory Usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 6, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(    rate(container_memory_usage_bytes{namespace=~\"$namespace\", container_name=\"node-chrome\"}[5m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  }
 ]
}