#!/bin/bash
scriptDir=$(dirname -- "$(readlink -f -- "$BASH_SOURCE")")

export ARN=$(kubectl get configmap revproxy-cert --output=jsonpath='{.data.revproxy_cert}')
if [[ ! -z $ARN ]]; then
  envsubst <$scriptDir/revproxy-service.yaml | kubectl apply -f -

else
  echo "Global configmap not configured"
fi
