#!groovy

pipeline {
  agent any

  stages {
    stage('FetchCode'){
      steps {
        //git url: "https://github.com/uc-cdis/cloud-automation.git", branch: 'fix/Jenkins'
        checkout scm
        dir('Secrets') {
            sh 'aws s3 cp s3://cdis-terraform-state/planx-pla.net/v1/config.tfvars config.tfvars'
            sh 'aws s3 cp s3://cdis-terraform-state/planx-pla.net/v1/backend.tfvars backend.tfvars'
        }
      }
    }
    stage('Prep') {
      steps {
        dir('Secrets') {
          sh 'terraform init -backend-config access_key=$AWS_ACCESS_KEY_ID -backend-config secret_key=$AWS_SECRET_ACCESS_KEY -backend-config backend.tfvars ../tf_files/aws'
        }
        dir('SecretsNoPlan') {
          sh 'cp ../Secrets/*.tfvars .'
          sh 'echo \'key = "noplan/terraform.tfstate"\' > noplan.tfvars'
          sh 'terraform init -backend-config access_key=$AWS_ACCESS_KEY_ID -backend-config secret_key=$AWS_SECRET_ACCESS_KEY -backend-config backend.tfvars --backend-config noplan.tfvars ../tf_files/aws'
        }
      }
    }
    stage('Plan - no state') {
      steps {
        dir('SecretsNoPlan') {
          echo 'Planning - no state ...'
          sh 'terraform plan --var aws_access_key=$AWS_ACCESS_KEY_ID --var aws_secret_key=$AWS_SECRET_ACCESS_KEY --var-file config.tfvars ../tf_files/aws'
        }
      }
    }
    stage('Plan planx-pla.net/v1 state') {
      steps {
        dir('Secrets') {
          echo 'Planning ...'
          sh 'terraform plan --var aws_access_key=$AWS_ACCESS_KEY_ID --var aws_secret_key=$AWS_SECRET_ACCESS_KEY --var-file config.tfvars -out plan.terraform ../tf_files/aws'
        }
      }
    }
    stage('Apply') {
      steps {
        timeout(time: 60, unit: 'SECONDS') {
          input 'Do you want to apply the terraform plan?'
        }
        echo 'Applying plan ...'
        dir('Secrets') {
          sh 'terraform apply plan.terraform'
        }
      }
    }
  }
}
